---
- hosts: wz
  remote_user: root
  tasks:
  - debug:
      msg: "test when condition (if)"
    #when: ansible_distribution == "CentOS" and ansible_distribution_version=="7.8"  #这个变量可以不用{{}}
    when:
    - ansible_distribution == "CentOS"   #在列表里的都要满足，相当于and
    - ansible_distribution_version=="7.8"
  - debug:
      msg: "{{item}}"
    with_items: [1,2,3,4,5,6]
    when: item >= 4
 

#说明
#==  :比较两个对象是否相等，相等为真
#
#!=  :比较两个对象是否不等，不等为真
#
#>   :比较两个值的大小，如果左边的值大于右边的值，则为真
#
#<  :比较两个值的大小，如果左边的值小于右边的值，则为真
#
#>=  :比较两个值的大小，如果左边的值大于右边的值或左右相等，则为真
#
#<=  :比较两个值的大小，如果左边的值小于右边的值或左右相等，则为真 
#
#and  :逻辑与，当左边与右边同时为真，则返回真
#
#or  :逻辑或，当左边与右边有任意一个为真，则返回真
#
#not  :取反，对一个操作体取反
#
#( )  :组合，将一组操作体包装在一起，形成一个较大的操作体
